services:
  nginx:
    image: nginx:alpine
    container_name: static-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./site:/usr/share/nginx/html:rw
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nodejs
    restart: unless-stopped

  nodejs:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: node-api
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/wallparadb
    volumes:
      - ./api:/usr/src/app:rw
      - /usr/src/app/node_modules
    expose:
      - 3000
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    restart: unless-stopped
